# Generated by Django 3.2.5 on 2022-06-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('UEN', models.CharField(max_length=200)),
                ('Industry', models.CharField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Documents', models.FileField(max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('Resume', models.FileField(max_length=200, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Salary', models.IntegerField()),
                ('Source', models.CharField(max_length=200)),
                ('JobDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedJobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobTitle', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200)),
                ('Salary', models.IntegerField()),
                ('JobDescription', models.CharField(max_length=200)),
            ],
        ),
    ]
