# Generated by Django 3.2.5 on 2022-06-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_auto_20220623_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedjoblisting',
            name='Hash',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
